### ISSUE TITLE
Dupe (not dupe, but you can make an higher level of a item, using only 1) bug in all electric machines in supreme.

### ISSUE THREAD

**Issue by davidcanas** [Slimefun-Addon-Community/Supreme#52] opened 2023-09-16 12:15 UTC
## Description (Required)
I found out that all supreme machines can be used to dupe, so if you want to make a magic sword and you only have 1 thornium sword, with this bug, you can easily solve this problem, you just need to create a netherite sword, rename it "&lThornium Sword" (in this case) and then craft normally, and use this sword instead of a real thornium sword.
There's also another bug, which is that when you craft an item, you can take one of them back from the machine, for example the most valuable one, and the craft continues...

## Steps to reproduce the Issue (Required)
- Craft an Electric Gear Fabricator (or other electric machine, the bug works with that too)
- Craft a thornium sword
- Craft a netherite sword
- Rename the netherite sword "Thornium Sword"
- Place the other materials in the machine 
- Place the two swords, the real one and the fake one
- That's it, the machine will recognize that the craft is valid... and you'll have an improved sword without spending 2 of them

## Expected behavior (Required)
Not recognizing the craft as valid.
Not being able to remove items during the crafting process, and the craft continuing...

## Server Log / Error Report
https://mclo.gs/IVzadAT

## Environment (Required)
https://prnt.sc/21a91YH135Qj

 - Minecraft Version: 1.20.1
 - CS-CoreLib Version: in 1.20 slimefun doesnt needs that
 - Slimefun Version: DEV - 1100 (git d683a633)
 - Plugin Version: vDev - 29
 (in the screenshot shows the versions)

https://github.com/Slimefun-Addon-Community/Supreme/assets/70149057/b7d55cc4-1377-47b4-b02c-d283423da4be

**Comment by davidcanas** [comment] 2023-12-18 17:16
.

**Comment by davidcanas** [comment] 2024-05-01 15:17
It has not been resolved yet .... It's possible to double everything with that. Spoiling the game experience.

**Comment by Boomer-1** [comment] 2024-06-01 01:24
rename is a command that's not available to players without being given perms from another addon outside of slimefun. that would be on that plugin to not allow it

**Comment by davidcanas** [comment] 2024-06-01 06:56
Players don't have access to  /rename, they're using Anvil.

They also don't have permission to use formatting codes (like &l) on the anvil, but the supreme recognizes it anyway

**Comment by Boomer-1** [comment] 2024-06-01 13:05
i've never seen an anvil renamed item get recognized by slimefun without the help of an external plugin. i can't replicate it

**Comment by davidcanas** [comment] 2024-06-01 13:14
Have you seen the vídeo? Just craft a normal netherite sword and rename it to "&l Netherite sword" on the anvil, for example.
After that, put a real thornium sword on top, and a fake one on the bottom, and he'll do A magic sword with only 1 sword.

Later I'll try to replicate it again, on that server I only had Supreme and slimefun, it was a test server that I created to prove it

**Comment by alvarophylipe** [comment] 2024-06-01 15:02
I've seen this same bug on several servers I joined. I contacted the administrators, and they didn't know how to proceed since the plugin hasn't been updated for a while. I decided to open a server with Slimefun and Supreme to test it, and I followed the exact steps described by @davidcanas. I was able to replicate the bug, and it affects all items that can be renamed in the anvil.

https://github.com/Slimefun-Addon-Community/Supreme/assets/87195703/17bb2043-b77e-40d1-8839-e7e98a8fd5c8

:D.

**Comment by davidcanas** [comment] 2024-06-01 15:12
Thank you, Álvaro, @alvarophylipe, for your testimony.

**Comment by lukariosmen** [comment] 2024-06-17 21:55
I made a temporary fix using the Minecraft plugin Skript. It's not perfect, but it blocks the ability to take items from the GUI.

Code:
```
on inventory click:
	if inventory name contains "&bElectric Magical Machine" or "&bElectric Core Machine" or "&bElectric Gear Machine" or "&bElectric Crafter":
		if event-inventoryaction is collect to cursor:
			cancel the event
		if slot 44 of event-inventory is dark gray stained glass pane:
			if "%slot 23 of event-inventory%" doesn't contain "&cInput a valid material to start":
				if event-slot is not 25:
					cancel the event
```

If you need help or have found a way to bypass this, contact me on Discord: lukariosmen.

**Comment by davidcanas** [comment] 2024-06-17 22:12
I really appreciate your help, @lukariosmen
TYSM :D

**Comment by RelativoBR** [comment] 2024-11-17 02:13
Correction related to this PR (https://github.com/Slimefun-Addon-Community/Supreme/pull/70)

**Comment by scorninpc** [comment] 2024-11-19 00:09
I can confirm that #70 works like a charm. Thank you

**Comment by scorninpc** [comment] 2024-12-02 03:01
This PR caused a new problem. For automated farms, the network cannot put all the items inside, and then start manufacturing the item.

This is how work without PR

https://github.com/user-attachments/assets/68f5c927-28ac-422a-977b-3f7ab6ee771b

And this is how work with PR

https://github.com/user-attachments/assets/f6d28d61-898d-45a2-9080-dd85db962481

As you can see, with PR network cannot fill all recipe. Anything that i can help?

**Comment by RelativoBR** [comment] 2024-12-02 16:35
Fixed in Supreme Build 3
https://blob.build/project/Supreme

**Closed by RelativoBR** 2024-12-02 16:35 UTC
Labels: bug

**Comment by davidcanas** [comment] 2024-12-12 20:41
Thank you all for solving this issue! ❤️
